### ISSUE TITLE
Report.Accession and Concept.local-name Query Parameters and Timeout Error 

### ISSUE THREAD

**Issue by tfoshag** [hamid-vakilzadeh/python-xbrl-us#7]
Hello, 
I have previously been running code to extract total assets and total revenues for specific SEC filings by using both the _report.accession_ parameter and _concept.local-name_ within my query. This was working for the past two months but something appears to have changed as using both the _report.accession_  and _concept.local-name_  parameters now seems to trigger a timeout error even when manually specifying longer timeout lengths such as 120 seconds. 

For example, the example query in the helpme for the module runs fine but if I replace the last two lines of parameters with the following:
`"report.accession": ['0000002178-20-000013']`

I receive a timeout error. However, if I remove the _concept.local-name_ parameter from this query and run it with just the _report.accession_ parameter then the query is able to complete successfully. So there seems to be so interaction effect between using the two parameters in tandem that is causing the query to not complete. 

I am using version 0.0.41 of the module given it allows for setting and returning limits greater than my XBRL US account as documented in #6 . 

Happy to troubleshoot whatever here but kind of at a loss on my end given using both parameters in a query was working a week ago but no longer appears to be. 

Thanks for all the help and developing this module. 
--Travis

**Comment by hamid-vakilzadeh** [comment]
Hi Travis,

Can you please provide the exact query you use so I can replicte the issue? 
Thanks,
Hamid

**Comment by tfoshag** [comment]
Of course. 

This is the query that times out 
`response = xbrl.query(
    method='fact search',
    parameters={
        "report.accession": ['0000002178-20-000013'],
        "concept.local-name": ['Assets']
    },
    fields=[
        'report.accession',
        'period.fiscal-year',
        'period.end',
        'period.fiscal-period',
        'fact.ultimus',
        'unit',
        'concept.local-name',
        'fact.value',
        'fact.id',
        'entity.id',
        'entity.cik',
        'entity.name',
        'report.sic-code',
    ],
    limit=100,
    as_dataframe=True
)`

This one is the that works when you remove the _concept.local-name_ parameter and just leave in _report.accession_
response = xbrl.query(
    method='fact search',
    parameters={
        "report.accession": ['0000002178-20-000013'],
    },
    fields=[
        'report.accession',
        'period.fiscal-year',
        'period.end',
        'period.fiscal-period',
        'fact.ultimus',
        'unit',
        'concept.local-name',
        'fact.value',
        'fact.id',
        'entity.id',
        'entity.cik',
        'entity.name',
        'report.sic-code',
    ],
    limit=100,
    as_dataframe=True
)

Thanks again, 
--Travis

**Comment by tfoshag** [comment]
Issue does not appear limited to version 0.0.41 as it also exists in version 0.0.43. 

Thanks!

**Comment by tfoshag** [comment]
Update on this issue: I am able to successfully complete queries that use both the _report.accession_ and the _concept.local-name_ parameter for specific combinations in which the _concept.local-name_ parameter is relatively more specialized. For generalized concepts such as "Assets", "Liabilities" or other such concepts there seems to be an efficiency issue compared to a week ago that I am unsure why it is occurring. 

The attached file has some examples of queries that use both parameters with documentation on how the query is currently performing. 

A week ago, Query 3 would execute in around 10 or 15 seconds. 

Thanks again for all the help here!
--Travis   
[20240510_Sample_Queries_Issue7.txt](https://github.com/hamid-vakilzadeh/python-xbrl-us/files/15279995/20240510_Sample_Queries_Issue7.txt)

**Comment by tfoshag** [comment]
Appears this issue may have been the result of something on the EDGAR portal end and not this module. All queries referenced in this issue execute within 0:01 seconds when using both a _concept.local-name_ and _report.accession_ parameter in the _fact search_ query. As such, marking the issue as closed. 

Thanks!
--Travis

**Comment by hamid-vakilzadeh** [comment]
Hi Travis,

As you guessed, this problem is beyond this package. But just to keep you updated, I have notified the XBRL.us team and would keep you updated as soon as I hear an update. 

Thanks for all your debugging efforts  😃

Best,
Hamid
